name: ci

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ARCH: amd64
  PATCH_FILE: Signal-Desktop.patch

jobs:
  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: |
          export SIGNAL_VERSION=$(cat ./SIGNAL_VERSION | head -n 1 | tr -d vV)
          echo "SIGNAL_VERSION=$SIGNAL_VERSION" >> $GITHUB_ENV
          echo "FEDORA_VERSION=$(cat ./FEDORA_VERSION | head -n 1)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(curl -s https://raw.githubusercontent.com/signalapp/Signal-Desktop/refs/tags/v$SIGNAL_VERSION/.nvmrc)" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=latest
      - uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6
        id: build-and-push
        with:
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARCH=${{ env.ARCH }}
            FEDORA_VERSION=${{ env.FEDORA_VERSION }}
            SIGNAL_VERSION=${{ env.SIGNAL_VERSION }}
            PATCH_FILE=patch/${{ env.PATCH_FILE }}
            NODE_VERSION=${{ env.NODE_VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  signal-desktop:
    needs: dockerfile
    if: needs.dockerfile.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: echo "SIGNAL_VERSION=$(cat ./SIGNAL_VERSION | head -n 1 | tr -d vV)" >> $GITHUB_ENV
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=latest
      - run: |
          mkdir -p ./output/
          docker run --rm -e SIGNAL_VERSION=${{ env.SIGNAL_VERSION }} -v ./output:/output:Z ${{ steps.meta.outputs.tags }}
